language: python
sudo: required

#dist:
#  trusty

python:
  - "3.5"

addons:
# Does not support 'CREATE SEQUENCE IF NOT EXISTS' in migration 0007.
#  postgresql: "9.4"

# Travis is all sorts of messed up when it comes to these
  postgresql: "9.5"
  packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - postgis
#  postgresql: "9.6"

postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

services:
  - postgresql

env:
  - DJANGO=1.10 DB=postgres ENV=TRAVIS

before_install:
#  - travis_retry wget https://bootstrap.pypa.io/get-pip.py
#  - python get-pip.py
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt update
  - sudo apt install postgresql-9.5 postgresql-contrib-9.5 postgis
  - sudo /etc/init.d/postgresql restart
  - psql --version
  - travis_wait 30 pip install -r requirements.txt
  - travis_wait 30 python -m nltk.downloader stopwords
  - travis_wait 30 python -m nltk.downloader names
  - travis_wait 30 python -m nltk.downloader cmudict
  - travis_wait 30 python -m nltk.downloader brown
  - travis_wait 30 python -m nltk.downloader punkt
  - travis_wait 30 python -m nltk.downloader averaged_perceptron_tagger
  - travis_wait 30 python -m nltk.downloader wordnet

before_script:
  - cp linsights/dbsettings.py.template linsights/dbsettings.py
  - psql -c 'create database travis_ci_test;' -U postgres
#  - "rake db:migrate"

script:
  - coverage run manage.py test app.tests

after_success:
  - codecov

# Temporarily
notifications:
  email: false
