language: python

services:
  - postgresql

matrix:
  include:
    - python: 3.4

before_install:
  - travis_retry wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install coverage==4.2
  - pip install Django==1.10.1
  - pip install nltk==3.2.1
  - pip install psycopg2==2.6.2
  - pip install SPLAT-library==0.4.2
  - pip install pexpect psutil matplotlib codecov nose termcolor sqlparse
  - travis_wait 30 python -m nltk.downloader stopwords
  - travis_wait 30 python -m nltk.downloader names
  - travis_wait 30 python -m nltk.downloader cmudict
  - travis_wait 30 python -m nltk.downloader brown
  - travis_wait 30 python -m nltk.downloader punkt
  - travis_wait 30 python -m nltk.downloader averaged_perceptron_tagger
  - travis_wait 30 python -m nltk.downloader wordnet
  - cp app/linsights/dbsettings.py.template app/linsights/dbsettings.py

test:
  adaptor: postgresql
  database: travis_ci_test
  username: postgres

#before_script:
#  - "psql -c 'create database travis_ci_test;' -U postgres"
#  - "rake db:migrate"

script:
  - ENV='TEST' coverage run manage.py test

after_success:
  - codecov
  - nosetests
