language: python

services:
  - postgresql

addons:
  postgresql: "9.5"

matrix:
  include:
    - python: 3.5

env:
  - DJANGO=1.10 DB=postgres ENV=TRAVIS

before_install:
  - travis_retry wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - travis_wait 30 pip install -r requirements.txt
  - travis_wait 30 python -m nltk.downloader stopwords
  - travis_wait 30 python -m nltk.downloader names
  - travis_wait 30 python -m nltk.downloader cmudict
  - travis_wait 30 python -m nltk.downloader brown
  - travis_wait 30 python -m nltk.downloader punkt
  - travis_wait 30 python -m nltk.downloader averaged_perceptron_tagger
  - travis_wait 30 python -m nltk.downloader wordnet

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

before_script:
  - cp linsights/dbsettings.py.template linsights/dbsettings.py
#  - "psql -c 'create database travis_ci_test;' -U postgres"
#  - "rake db:migrate"

script:
  - coverage run manage.py test

after_success:
  - codecov
  - nosetests

# Temporarily
notifications:
  email: false
